version: '3'
services:
  # prometheus json exporter
  cosmonitor:
    image: graziottil/cosmonitor:latest
    container_name: cosmonitor
    environment:
      NODE_RPC: "http://host.docker.internal:26657"
    ports:
      - "9110:9090"
    extra_hosts:
      # let the container access the host network (needs to access the node rpc endpoint)
      - "host.docker.internal:host-gateway"

  # prometheus server
  prometheus:
    image: prom/prometheus:latest
    container_name: monitor-prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/config.yml'
      - '--log.level=debug'
    ports:
      - "39090:9090"
    extra_hosts:
      # let the container access the host network (needs to access the node prometheus endpoint)
      - "host.docker.internal:host-gateway"

  # node hardware prometheus exporter
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100"

networks:
  monitoring:

volumes:
  prometheus-data:
    driver: local