version: '3'
services:
  # prometheus server
  prometheus:
    image: prom/prometheus:latest
    container_name: monitor-prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/config.yml'
      - '--log.level=debug'
    ports:
      - "9090:9090"
networks:
  monitoring:
